curl -X POST http://localhost:8702/api/books -d "title=The Enchanted Forest&author=Ella Rivers&year=2001&genre=Fiction"
curl -X POST http://localhost:8702/api/books -d "title=Journey to the Unknown&author=Maxwell Carter&year=2002&genre=Non-Fiction"
curl -X POST http://localhost:8702/api/books -d "title=Mystery of the Lost Village&author=Lara Mason&year=2003&genre=Mystery"
curl -X POST http://localhost:8702/api/books -d "title=Beyond the Stars&author=Orion Blake&year=2004&genre=Science Fiction"
curl -X POST http://localhost:8702/api/books -d "title=The Dragon's Quest&author=Fiona Drake&year=2005&genre=Fantasy"
curl -X POST http://localhost:8702/api/books -d "title=Life of a Legend&author=Noah King&year=2006&genre=Biography"
curl -X POST http://localhost:8702/api/books -d "title=The Hidden Truth&author=Ava Sinclair&year=2007&genre=Thriller"
curl -X POST http://localhost:8702/api/books -d "title=Echoes of the Past&author=Ethan Hart&year=2008&genre=Historical"
curl -X POST http://localhost:8702/api/books -d "title=Whispers in the Wind&author=Isabella Frost&year=2009&genre=Romance"
curl -X POST http://localhost:8702/api/books -d "title=Secrets of the Jungle&author=Samuel Reed&year=2010&genre=Adventure"
curl -X POST http://localhost:8702/api/books -d "title=The Forbidden Path&author=Olivia Bennett&year=2011&genre=Fantasy"
curl -X POST http://localhost:8702/api/books -d "title=Chronicles of the Unknown&author=Henry Turner&year=2012&genre=Science Fiction"
curl -X POST http://localhost:8702/api/books -d "title=The Silent Witness&author=Grace Campbell&year=2013&genre=Mystery"
curl -X POST http://localhost:8702/api/books -d "title=Rise of the Phoenix&author=Lucas Morgan&year=2014&genre=Fantasy"
curl -X POST http://localhost:8702/api/books -d "title=Shadows of the Night&author=Emily Scott&year=2015&genre=Thriller"
curl -X POST http://localhost:8702/api/books -d "title=The Endless Horizon&author=Alexander Gray&year=2016&genre=Science Fiction"
curl -X POST http://localhost:8702/api/books -d "title=Guardians of the Realm&author=Charlotte Lee&year=2017&genre=Fantasy"
curl -X POST http://localhost:8702/api/books -d "title=The Vanishing Point&author=James Clark&year=2018&genre=Mystery"
curl -X POST http://localhost:8702/api/books -d "title=The Last Expedition&author=Sophia Turner&year=2019&genre=Adventure"
curl -X POST http://localhost:8702/api/books -d "title=Legacy of the Ancients&author=Daniel Hill&year=2020&genre=Adventure"
curl -X POST http://localhost:8702/api/books -d "title=AdventureBook&author=Lily Lee&year=2020&genre=Adventure"